"""empty message

Revision ID: 8caae3eaea7f
Revises: ee2ee25a787c
Create Date: 2021-05-22 20:49:50.264846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8caae3eaea7f'
down_revision = 'ee2ee25a787c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'contracts', 'customers', ['user_id'], ['id'])
    op.add_column('deliveries', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'deliveries', 'customers', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'deliveries', type_='foreignkey')
    op.drop_column('deliveries', 'user_id')
    op.drop_constraint(None, 'contracts', type_='foreignkey')
    op.drop_column('contracts', 'user_id')
    # ### end Alembic commands ###
