"""empty message

Revision ID: d3ee27c6846b
Revises: f72f0727ea68
Create Date: 2021-05-22 19:39:09.528226

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd3ee27c6846b'
down_revision = 'f72f0727ea68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('customers_ibfk_1', 'customers', type_='foreignkey')
    op.drop_column('customers', 'role_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('role_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('customers_ibfk_1', 'customers', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###
