"""empty message

Revision ID: ee2ee25a787c
Revises: d3ee27c6846b
Create Date: 2021-05-22 20:03:53.826883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee2ee25a787c'
down_revision = 'd3ee27c6846b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('role_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'customers', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.drop_column('customers', 'role_id')
    # ### end Alembic commands ###
